import type {
  Bay,
  InventoryItem,
  Mechanic,
  WorkOrder,
} from '../types/workshop';

const STORAGE_KEY_PREFIX = 'fratelli_front_v1_';

export const INITIAL_MECHANICS: Mechanic[] = [
  {
    id: 'MEC-01',
    name: 'Juan Carlos Mamani',
    nickname: 'J.C. Mamani',
    specialty: 'Mecánica General',
    activeOtCount: 2,
    currentBayId: 1,
    phone: '+591 71234567',
  },
  {
    id: 'MEC-02',
    name: 'Roberto Gómez Silva',
    nickname: 'R. Gómez',
    specialty: 'Frenos y Suspensión',
    activeOtCount: 1,
    currentBayId: 2,
    phone: '+591 72345678',
  },
  {
    id: 'MEC-03',
    name: 'Diego Morales Claros',
    nickname: 'D. Morales',
    specialty: 'Electricidad y Diagnóstico',
    activeOtCount: 1,
    currentBayId: 3,
    phone: '+591 73456789',
  },
  {
    id: 'MEC-04',
    name: 'Marco Vargas Rios',
    nickname: 'M. Vargas',
    specialty: 'Transmisiones',
    activeOtCount: 0,
    currentBayId: undefined,
    phone: '+591 74567890',
  },
];

export const INITIAL_BAYS: Bay[] = [
  {
    id: 1,
    code: 'BAHIA-01',
    name: 'Bahía 1: Elevador 4T (Mecánica Pesada)',
    type: 'Elevador Hidráulico 4T',
    status: 'OCUPADA',
    currentWorkOrderId: 'OT-2025-0101',
    currentVehiclePlate: '4589-KXA',
    currentVehicleModel: 'Toyota Hilux 2.8 TD 2021',
    primaryMechanicId: 'MEC-01',
    assistantMechanicId: 'MEC-04',
    startedAt: '2025-05-10T08:30:00Z',
    estimatedCompletionAt: '2025-05-12T17:00:00Z',
    notes: 'Cambio de amortiguadores delanteros y calibración de inyectores.',
  },
  {
    id: 2,
    code: 'BAHIA-02',
    name: 'Bahía 2: Elevador 2 Col. (Frenos y Suspensión)',
    type: 'Elevador 2 Columnas',
    status: 'ESPERA_REPUESTO',
    currentWorkOrderId: 'OT-2025-0102',
    currentVehiclePlate: '3042-XYZ',
    currentVehicleModel: 'Suzuki Grand Vitara 2019',
    primaryMechanicId: 'MEC-02',
    startedAt: '2025-05-09T14:00:00Z',
    estimatedCompletionAt: '2025-05-13T12:00:00Z',
    notes: 'Esperando llegada de kit de embrague reforzado.',
  },
  {
    id: 3,
    code: 'BAHIA-03',
    name: 'Bahía 3: Fosa / Diagnóstico Computarizado',
    type: 'Fosa de Alineación',
    status: 'OCUPADA',
    currentWorkOrderId: 'OT-2025-0105',
    currentVehiclePlate: '2190-LPN',
    currentVehicleModel: 'Nissan Frontier 2.5 2018',
    primaryMechanicId: 'MEC-03',
    startedAt: '2025-05-11T09:00:00Z',
    estimatedCompletionAt: '2025-05-12T14:00:00Z',
    notes: 'Trabajo suspendido por detección de fuga de retén adicional (RN-03).',
  },
  {
    id: 4,
    code: 'BAHIA-04',
    name: 'Bahía 4: Mantenimiento Preventivo / Rápido',
    type: 'Bahía Rápida / Escáner',
    status: 'LIBRE',
    currentWorkOrderId: undefined,
    currentVehiclePlate: undefined,
    currentVehicleModel: undefined,
    primaryMechanicId: undefined,
    notes: 'Disponible para asignación de mantenimiento express o afinado.',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'REP-MOT-001',
    code: 'REP-MOT-001',
    name: 'Kit Correa de Distribución + Tensor Gates',
    category: 'MOTOR',
    brand: 'Gates',
    compatibleModels: 'Toyota Hilux 2.4/2.8, Fortuner',
    stockAvailable: 8,
    stockReserved: 1,
    stockMinimum: 3,
    unitCostBOB: 420,
    unitPriceBOB: 680,
    locationShelf: 'Estante A-01',
    lastMovementDate: '2025-05-08',
    daysWithoutMovement: 3,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-MOT-002',
    code: 'REP-MOT-002',
    name: 'Bomba de Agua GMB Reforzada',
    category: 'MOTOR',
    brand: 'GMB',
    compatibleModels: 'Suzuki Grand Vitara 2.0/2.4',
    stockAvailable: 4,
    stockReserved: 1,
    stockMinimum: 2,
    unitCostBOB: 280,
    unitPriceBOB: 450,
    locationShelf: 'Estante A-02',
    lastMovementDate: '2025-04-12',
    daysWithoutMovement: 29,
    rotationCategory: 'MEDIA',
  },
  {
    id: 'REP-MOT-003',
    code: 'REP-MOT-003',
    name: 'Juego de Bujías de Iridio NGK (x4)',
    category: 'MOTOR',
    brand: 'NGK Laser Iridium',
    compatibleModels: 'Universal Gasolina / Toyota / Nissan',
    stockAvailable: 24,
    stockReserved: 4,
    stockMinimum: 8,
    unitCostBOB: 180,
    unitPriceBOB: 320,
    locationShelf: 'Estante A-03',
    lastMovementDate: '2025-05-10',
    daysWithoutMovement: 1,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-MOT-004',
    code: 'REP-MOT-004',
    name: 'Retén Trasero de Cigüeñal (Bancada) Original',
    category: 'MOTOR',
    brand: 'Corteco / OEM',
    compatibleModels: 'Nissan Frontier YD25 / NP300',
    stockAvailable: 6,
    stockReserved: 1,
    stockMinimum: 2,
    unitCostBOB: 110,
    unitPriceBOB: 210,
    locationShelf: 'Estante A-04',
    lastMovementDate: '2025-05-11',
    daysWithoutMovement: 0,
    rotationCategory: 'MEDIA',
  },
  {
    id: 'REP-FRE-001',
    code: 'REP-FRE-001',
    name: 'Pastillas de Freno Cerámicas Delanteras Brembo',
    category: 'FRENOS',
    brand: 'Brembo',
    compatibleModels: 'Toyota Hilux, Fortuner 2016-2023',
    stockAvailable: 12,
    stockReserved: 2,
    stockMinimum: 4,
    unitCostBOB: 240,
    unitPriceBOB: 390,
    locationShelf: 'Estante B-01',
    lastMovementDate: '2025-05-09',
    daysWithoutMovement: 2,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-FRE-002',
    code: 'REP-FRE-002',
    name: 'Discos de Freno Ventilados Delanteros (Par)',
    category: 'FRENOS',
    brand: 'Fremax',
    compatibleModels: 'Suzuki Grand Vitara / SX4',
    stockAvailable: 3,
    stockReserved: 0,
    stockMinimum: 2,
    unitCostBOB: 490,
    unitPriceBOB: 780,
    locationShelf: 'Estante B-02',
    lastMovementDate: '2025-04-20',
    daysWithoutMovement: 21,
    rotationCategory: 'MEDIA',
  },
  {
    id: 'REP-FRE-003',
    code: 'REP-FRE-003',
    name: 'Líquido de Frenos DOT 4 Bosch 1L',
    category: 'FRENOS',
    brand: 'Bosch',
    compatibleModels: 'Universal',
    stockAvailable: 35,
    stockReserved: 3,
    stockMinimum: 10,
    unitCostBOB: 45,
    unitPriceBOB: 85,
    locationShelf: 'Estante B-03',
    lastMovementDate: '2025-05-10',
    daysWithoutMovement: 1,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-SUS-001',
    code: 'REP-SUS-001',
    name: 'Amortiguador Delantero a Gas KYB Excel-G (Unidad)',
    category: 'SUSPENSION_DIRECCION',
    brand: 'KYB',
    compatibleModels: 'Toyota Hilux 4x4 2016-2022',
    stockAvailable: 4,
    stockReserved: 2,
    stockMinimum: 2,
    unitCostBOB: 520,
    unitPriceBOB: 840,
    locationShelf: 'Estante C-01',
    lastMovementDate: '2025-05-09',
    daysWithoutMovement: 2,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-TRA-001',
    code: 'REP-TRA-001',
    name: 'Kit de Embrague Completo (Disco, Prensa y Rulemán) Valeo',
    category: 'TRANSMISION',
    brand: 'Valeo',
    compatibleModels: 'Suzuki Grand Vitara 2.4',
    stockAvailable: 2,
    stockReserved: 1,
    stockMinimum: 1,
    unitCostBOB: 890,
    unitPriceBOB: 1450,
    locationShelf: 'Estante D-01',
    lastMovementDate: '2025-05-09',
    daysWithoutMovement: 2,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-TRA-002',
    code: 'REP-TRA-002',
    name: 'Aceite de Transmisión Manual 75W-90 Motul Motylgear 1L',
    category: 'TRANSMISION',
    brand: 'Motul',
    compatibleModels: 'Universal Cajas Manuales y Diferenciales',
    stockAvailable: 22,
    stockReserved: 4,
    stockMinimum: 8,
    unitCostBOB: 80,
    unitPriceBOB: 140,
    locationShelf: 'Estante D-02',
    lastMovementDate: '2025-05-07',
    daysWithoutMovement: 4,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-FLT-001',
    code: 'REP-FLT-001',
    name: 'Filtro de Aceite Blindado Mann-Filter W 68/3',
    category: 'FILTROS_FLUIDOS',
    brand: 'Mann-Filter',
    compatibleModels: 'Toyota / Suzuki / Nissan',
    stockAvailable: 48,
    stockReserved: 6,
    stockMinimum: 15,
    unitCostBOB: 35,
    unitPriceBOB: 65,
    locationShelf: 'Estante E-01',
    lastMovementDate: '2025-05-11',
    daysWithoutMovement: 0,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-FLT-002',
    code: 'REP-FLT-002',
    name: 'Filtro de Aire Motor Donaldson Alta Eficiencia',
    category: 'FILTROS_FLUIDOS',
    brand: 'Donaldson',
    compatibleModels: 'Toyota Hilux 2.8 TD 2016+',
    stockAvailable: 15,
    stockReserved: 2,
    stockMinimum: 5,
    unitCostBOB: 95,
    unitPriceBOB: 160,
    locationShelf: 'Estante E-02',
    lastMovementDate: '2025-05-09',
    daysWithoutMovement: 2,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-FLT-003',
    code: 'REP-FLT-003',
    name: 'Aceite de Motor Sintético 5W-30 Mobil 1 ESP (Galón 4L)',
    category: 'FILTROS_FLUIDOS',
    brand: 'Mobil 1',
    compatibleModels: 'Gasolina / Diésel Liviano',
    stockAvailable: 18,
    stockReserved: 3,
    stockMinimum: 6,
    unitCostBOB: 290,
    unitPriceBOB: 460,
    locationShelf: 'Estante E-03',
    lastMovementDate: '2025-05-11',
    daysWithoutMovement: 0,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-FLT-004',
    code: 'REP-FLT-004',
    name: 'Filtro de Combustible Diésel Separador de Agua Denso',
    category: 'FILTROS_FLUIDOS',
    brand: 'Denso',
    compatibleModels: 'Nissan Frontier / Mitsubishi L200',
    stockAvailable: 8,
    stockReserved: 1,
    stockMinimum: 3,
    unitCostBOB: 120,
    unitPriceBOB: 210,
    locationShelf: 'Estante E-04',
    lastMovementDate: '2025-05-04',
    daysWithoutMovement: 7,
    rotationCategory: 'MEDIA',
  },
  {
    id: 'REP-CLI-001',
    code: 'REP-CLI-001',
    name: 'Filtro de Cabina / Polen con Carbón Activado Mann',
    category: 'CLIMATIZACION',
    brand: 'Mann-Filter',
    compatibleModels: 'Toyota Hilux / Fortuner / RAV4',
    stockAvailable: 14,
    stockReserved: 1,
    stockMinimum: 4,
    unitCostBOB: 65,
    unitPriceBOB: 125,
    locationShelf: 'Estante G-01',
    lastMovementDate: '2025-05-09',
    daysWithoutMovement: 2,
    rotationCategory: 'ALTA',
  },
];

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'ot-001',
    code: 'OT-2025-0101',
    vehiclePlate: '4589-KXA',
    vehicleBrand: 'Toyota',
    vehicleModel: 'Hilux D/C 4x4 2021',
    vehicleYear: 2021,
    clientName: 'Alejandro Valenzuela',
    clientDocument: '4892019 LP',
    clientPhone: '+591 70192834',
    clientEmail: 'alejandro.val@gmail.com',
    status: 'EN_PROGRESO',
    assignedBayId: 1,
    primaryMechanicId: 'MEC-01',
    assistantMechanicId: 'MEC-04',
    entryDate: '2025-05-10T08:30:00Z',
    estimatedDeliveryDate: '2025-05-12T17:00:00Z',
    entryReason:
      'Ruido metálico en tren delantero al pasar baches y mantenimiento de 60,000 km.',
    diagnosticReport:
      'Amortiguadores delanteros con fuga de aceite hidráulico. Desgaste severo en pastillas de freno (quedan 1.5mm).',
    diagnosticDate: '2025-05-10T09:30:00Z',
    laborItems: [
      {
        id: 'lab-01',
        description: 'Reemplazo de amortiguadores delanteros y alineación láser',
        estimatedHours: 3.5,
        hourlyRateBOB: 120,
        totalBOB: 420,
        isCompleted: true,
        assignedMechanicId: 'MEC-01',
      },
      {
        id: 'lab-02',
        description: 'Cambio de pastillas de freno y purgado de circuito hidráulico',
        estimatedHours: 1.5,
        hourlyRateBOB: 120,
        totalBOB: 180,
        isCompleted: false,
        assignedMechanicId: 'MEC-04',
      },
    ],
    partsItems: [
      {
        id: 'pot-01',
        partId: 'REP-SUS-001',
        partCode: 'REP-SUS-001',
        description: 'Amortiguador Delantero a Gas KYB Excel-G (Unidad)',
        quantityRequired: 2,
        quantityUsed: 2,
        unitPriceBOB: 840,
        totalBOB: 1680,
        isReserved: true,
        isDeliveredToBay: true,
        status: 'INSTALADO',
      },
      {
        id: 'pot-02',
        partId: 'REP-FRE-001',
        partCode: 'REP-FRE-001',
        description: 'Pastillas de Freno Cerámicas Delanteras Brembo',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 390,
        totalBOB: 390,
        isReserved: true,
        isDeliveredToBay: true,
        status: 'RESERVADO',
      },
      {
        id: 'pot-03',
        partId: 'REP-FLT-003',
        partCode: 'REP-FLT-003',
        description: 'Aceite de Motor Sintético 5W-30 Mobil 1 ESP (Galón)',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 460,
        totalBOB: 460,
        isReserved: true,
        isDeliveredToBay: false,
        status: 'RESERVADO',
      },
    ],
    totalLaborBOB: 600,
    totalPartsBOB: 2530,
    totalGeneralBOB: 3130,
    clientApprovedAt: '2025-05-10T10:15:00Z',
    clientApprovalMethod: 'PORTAL_WEB',
    lastClientContactDate: '2025-05-10',
    daysWithoutClientResponse: 0,
    hasPendingAdditionalWork: false,
    isSuspendedForAdditionalWork: false,
    statusHistory: [
      { status: 'REGISTRADA', timestamp: '2025-05-10T08:30:00Z', changedBy: 'Recepción (Ana Morales)' },
      { status: 'EN_DIAGNOSTICO', timestamp: '2025-05-10T09:00:00Z', changedBy: 'Juan Carlos Mamani' },
      { status: 'DIAGNOSTICADA', timestamp: '2025-05-10T09:30:00Z', changedBy: 'Juan Carlos Mamani' },
      { status: 'APROBADA', timestamp: '2025-05-10T10:15:00Z', changedBy: 'Cliente (Portal Web)' },
      { status: 'EN_PROGRESO', timestamp: '2025-05-10T11:00:00Z', changedBy: 'Jefe Taller (Asignado a Bahía 1)' },
    ],
    mechanicNotes: 'Amortiguadores instalados y torqueados según manual de fábrica (115 Nm).',
  },
  {
    id: 'ot-002',
    code: 'OT-2025-0102',
    vehiclePlate: '3042-XYZ',
    vehicleBrand: 'Suzuki',
    vehicleModel: 'Grand Vitara 2.4 2019',
    vehicleYear: 2019,
    clientName: 'Carla Patricia Mendoza',
    clientDocument: '6102938 SC',
    clientPhone: '+591 76543210',
    clientEmail: 'carla.mendoza@hotmail.com',
    status: 'EN_ESPERA_REPUESTO',
    assignedBayId: 2,
    primaryMechanicId: 'MEC-02',
    entryDate: '2025-05-09T14:00:00Z',
    estimatedDeliveryDate: '2025-05-13T12:00:00Z',
    entryReason: 'Pedal de embrague muy duro y patina en subidas pronunciadas.',
    diagnosticReport:
      'Disco de embrague desgastado hasta los remaches, placa recalentada con fatiga térmica. Requiere kit de embrague completo.',
    diagnosticDate: '2025-05-09T15:10:00Z',
    laborItems: [
      {
        id: 'lab-04',
        description: 'Desmontaje de caja de cambios, reemplazo kit de embrague y montaje',
        estimatedHours: 6.0,
        hourlyRateBOB: 120,
        totalBOB: 720,
        isCompleted: false,
        assignedMechanicId: 'MEC-02',
      },
      {
        id: 'lab-05',
        description: 'Envío y control de rectificado de volante bimasa',
        estimatedHours: 1.0,
        hourlyRateBOB: 120,
        totalBOB: 120,
        isCompleted: true,
        assignedMechanicId: 'MEC-02',
      },
    ],
    partsItems: [
      {
        id: 'pot-05',
        partId: 'REP-TRA-001',
        partCode: 'REP-TRA-001',
        description: 'Kit de Embrague Completo (Disco, Prensa y Rulemán) Valeo',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 1450,
        totalBOB: 1450,
        isReserved: true,
        isDeliveredToBay: false,
        status: 'EN_ESPERA_IMPORTACION',
      },
      {
        id: 'pot-06',
        partId: 'REP-TRA-002',
        partCode: 'REP-TRA-002',
        description: 'Aceite de Transmisión Manual 75W-90 Motul 1L',
        quantityRequired: 3,
        quantityUsed: 0,
        unitPriceBOB: 140,
        totalBOB: 420,
        isReserved: true,
        isDeliveredToBay: false,
        status: 'RESERVADO',
      },
    ],
    totalLaborBOB: 840,
    totalPartsBOB: 1870,
    totalGeneralBOB: 2710,
    clientApprovedAt: '2025-05-09T16:00:00Z',
    clientApprovalMethod: 'WHATSAPP_CONFIRMADO',
    lastClientContactDate: '2025-05-11',
    daysWithoutClientResponse: 0,
    hasPendingAdditionalWork: false,
    isSuspendedForAdditionalWork: false,
    statusHistory: [
      { status: 'REGISTRADA', timestamp: '2025-05-09T14:00:00Z', changedBy: 'Recepción' },
      { status: 'EN_DIAGNOSTICO', timestamp: '2025-05-09T14:30:00Z', changedBy: 'Roberto Gómez' },
      { status: 'DIAGNOSTICADA', timestamp: '2025-05-09T15:10:00Z', changedBy: 'Roberto Gómez' },
      { status: 'APROBADA', timestamp: '2025-05-09T16:00:00Z', changedBy: 'Cliente WhatsApp' },
      { status: 'EN_PROGRESO', timestamp: '2025-05-09T16:30:00Z', changedBy: 'Roberto Gómez' },
      { status: 'EN_ESPERA_REPUESTO', timestamp: '2025-05-10T10:00:00Z', changedBy: 'Jefe Taller (Demora proveedor Valeo)' },
    ],
    mechanicNotes: 'Caja bajada. Volante rectificado ya llegó. Esperando kit de embrague Valeo.',
  },
  {
    id: 'ot-003',
    code: 'OT-2025-0103',
    vehiclePlate: '5120-TUV',
    vehicleBrand: 'Hyundai',
    vehicleModel: 'Tucson 2.0 GL 2020',
    vehicleYear: 2020,
    clientName: 'Rodrigo Fernández Paz',
    clientDocument: '3490182 CB',
    clientPhone: '+591 77112233',
    clientEmail: 'r.fernandez@pazcorp.bo',
    status: 'DIAGNOSTICADA',
    assignedBayId: undefined,
    primaryMechanicId: 'MEC-03',
    entryDate: '2025-04-24T10:00:00Z',
    estimatedDeliveryDate: '2025-05-18T18:00:00Z',
    entryReason: 'Check Engine encendido y pérdida súbita de potencia al acelerar en pendientes.',
    diagnosticReport:
      'Falla en bobinas de encendido cilindro 2 y 4 + sensor de oxígeno banco 1 descalibrado.',
    diagnosticDate: '2025-04-24T15:00:00Z',
    laborItems: [
      {
        id: 'lab-06',
        description: 'Diagnóstico escáner avanzado y reemplazo de bobinas con bujías',
        estimatedHours: 2.0,
        hourlyRateBOB: 120,
        totalBOB: 240,
        isCompleted: false,
      },
    ],
    partsItems: [
      {
        id: 'pot-07',
        partId: 'REP-MOT-003',
        partCode: 'REP-MOT-003',
        description: 'Juego de Bujías de Iridio NGK (x4)',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 320,
        totalBOB: 320,
        isReserved: false,
        isDeliveredToBay: false,
        status: 'PENDIENTE',
      },
    ],
    totalLaborBOB: 240,
    totalPartsBOB: 320,
    totalGeneralBOB: 560,
    clientApprovedAt: undefined,
    lastClientContactDate: '2025-04-25',
    daysWithoutClientResponse: 17,
    hasPendingAdditionalWork: false,
    isSuspendedForAdditionalWork: false,
    statusHistory: [
      { status: 'REGISTRADA', timestamp: '2025-04-24T10:00:00Z', changedBy: 'Recepción' },
      { status: 'EN_DIAGNOSTICO', timestamp: '2025-04-24T13:00:00Z', changedBy: 'Diego Morales' },
      { status: 'DIAGNOSTICADA', timestamp: '2025-04-24T15:00:00Z', changedBy: 'Diego Morales' },
    ],
    internalNotes: 'ALERTA RN-06: 17 días sin respuesta del cliente.',
  },
  {
    id: 'ot-004',
    code: 'OT-2025-0104',
    vehiclePlate: '4011-HBN',
    vehicleBrand: 'Toyota',
    vehicleModel: 'Corolla 1.8 Hybrid 2022',
    vehicleYear: 2022,
    clientName: 'Mariana Gutierrez Arce',
    clientDocument: '7829103 SC',
    clientPhone: '+591 78901234',
    clientEmail: 'mariana.g@gmail.com',
    status: 'APROBADA',
    assignedBayId: undefined,
    primaryMechanicId: 'MEC-01',
    entryDate: '2025-05-11T14:30:00Z',
    estimatedDeliveryDate: '2025-05-13T16:00:00Z',
    entryReason:
      'Mantenimiento de 30,000 km, rotación de neumáticos y revisión de sistema de frenos regenerativos.',
    diagnosticReport:
      'Vehículo híbrido en excelente estado. Requiere cambio de aceite sintético 0W-20, filtro de aceite y cabina.',
    diagnosticDate: '2025-05-11T15:20:00Z',
    laborItems: [
      {
        id: 'lab-07',
        description: 'Mantenimiento programado 30,000 km + Inspección híbrida',
        estimatedHours: 2.0,
        hourlyRateBOB: 120,
        totalBOB: 240,
        isCompleted: false,
      },
    ],
    partsItems: [
      {
        id: 'pot-08',
        partId: 'REP-FLT-001',
        partCode: 'REP-FLT-001',
        description: 'Filtro de Aceite Blindado Mann-Filter W 68/3',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 65,
        totalBOB: 65,
        isReserved: true,
        isDeliveredToBay: false,
        status: 'RESERVADO',
      },
      {
        id: 'pot-09',
        partId: 'REP-CLI-001',
        partCode: 'REP-CLI-001',
        description: 'Filtro de Cabina con Carbón Activado Mann',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 125,
        totalBOB: 125,
        isReserved: true,
        isDeliveredToBay: false,
        status: 'RESERVADO',
      },
    ],
    totalLaborBOB: 240,
    totalPartsBOB: 190,
    totalGeneralBOB: 430,
    clientApprovedAt: '2025-05-11T16:00:00Z',
    clientApprovalMethod: 'PORTAL_WEB',
    lastClientContactDate: '2025-05-11',
    daysWithoutClientResponse: 0,
    hasPendingAdditionalWork: false,
    isSuspendedForAdditionalWork: false,
    statusHistory: [
      { status: 'REGISTRADA', timestamp: '2025-05-11T14:30:00Z', changedBy: 'Recepción' },
      { status: 'EN_DIAGNOSTICO', timestamp: '2025-05-11T15:00:00Z', changedBy: 'Juan Carlos Mamani' },
      { status: 'DIAGNOSTICADA', timestamp: '2025-05-11T15:20:00Z', changedBy: 'Juan Carlos Mamani' },
      { status: 'APROBADA', timestamp: '2025-05-11T16:00:00Z', changedBy: 'Cliente (Portal Web)' },
    ],
    internalNotes: 'Cliente aprobó de inmediato. Asignar a Bahía 4 apenas termine turno.',
  },
  {
    id: 'ot-005',
    code: 'OT-2025-0105',
    vehiclePlate: '2190-LPN',
    vehicleBrand: 'Nissan',
    vehicleModel: 'Frontier NP300 2018',
    vehicleYear: 2018,
    clientName: 'Jorge Alberto Quiroga',
    clientDocument: '2981045 LP',
    clientPhone: '+591 71982374',
    clientEmail: 'jorge.quiroga@transporte.bo',
    status: 'DIAGNOSTICADA',
    assignedBayId: 3,
    primaryMechanicId: 'MEC-03',
    entryDate: '2025-05-11T09:00:00Z',
    estimatedDeliveryDate: '2025-05-14T17:00:00Z',
    entryReason: 'Cambio de pastillas de freno y cambio de aceite de motor.',
    diagnosticReport:
      'Durante la inspección en elevador, se detectó FUGA ACTIVA DE ACEITE en el Retén Trasero de Cigüeñal (Bancada).',
    diagnosticDate: '2025-05-11T10:30:00Z',
    laborItems: [
      {
        id: 'lab-08',
        description: 'Cambio básico de aceite y filtro',
        estimatedHours: 1.0,
        hourlyRateBOB: 120,
        totalBOB: 120,
        isCompleted: true,
        assignedMechanicId: 'MEC-03',
      },
      {
        id: 'lab-09',
        description: '[ADICIONAL RN-03] Desmontaje de caja y reemplazo de retén de bancada',
        estimatedHours: 4.5,
        hourlyRateBOB: 120,
        totalBOB: 540,
        isCompleted: false,
        assignedMechanicId: 'MEC-03',
      },
    ],
    partsItems: [
      {
        id: 'pot-10',
        partId: 'REP-FLT-001',
        partCode: 'REP-FLT-001',
        description: 'Filtro de Aceite Blindado Mann-Filter W 68/3',
        quantityRequired: 1,
        quantityUsed: 1,
        unitPriceBOB: 65,
        totalBOB: 65,
        isReserved: true,
        isDeliveredToBay: true,
        status: 'INSTALADO',
      },
      {
        id: 'pot-11',
        partId: 'REP-MOT-004',
        partCode: 'REP-MOT-004',
        description: '[ADICIONAL RN-03] Retén Trasero de Cigüeñal Original',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 210,
        totalBOB: 210,
        isReserved: true,
        isDeliveredToBay: false,
        status: 'PENDIENTE',
      },
    ],
    totalLaborBOB: 660,
    totalPartsBOB: 275,
    totalGeneralBOB: 935,
    clientApprovedAt: undefined,
    lastClientContactDate: '2025-05-11',
    daysWithoutClientResponse: 0,
    hasPendingAdditionalWork: true,
    additionalWorkDescription:
      'Detección de fuga activa de aceite en retén de bancada. Requiere desmontar caja de cambios.',
    additionalWorkCostBOB: 750,
    isSuspendedForAdditionalWork: true,
    statusHistory: [
      { status: 'REGISTRADA', timestamp: '2025-05-11T09:00:00Z', changedBy: 'Recepción' },
      { status: 'EN_DIAGNOSTICO', timestamp: '2025-05-11T10:00:00Z', changedBy: 'Diego Morales' },
      { status: 'DIAGNOSTICADA', timestamp: '2025-05-11T10:30:00Z', changedBy: 'Diego Morales (Detectó daño adicional)' },
    ],
    mechanicNotes: 'ATENCIÓN RN-03: Fuga severa en retén. No armar hasta autorización del cliente.',
  },
  {
    id: 'ot-007',
    code: 'OT-2025-0107',
    vehiclePlate: '7830-PQM',
    vehicleBrand: 'Chevrolet',
    vehicleModel: 'Cruze LTZ 1.4T 2019',
    vehicleYear: 2019,
    clientName: 'Luis Alberto Rojas',
    clientDocument: '4581207 LP',
    clientPhone: '+591 70889900',
    clientEmail: 'luis.rojas@gmail.com',
    status: 'REGISTRADA',
    assignedBayId: undefined,
    primaryMechanicId: undefined,
    entryDate: '2025-05-12T09:00:00Z',
    estimatedDeliveryDate: undefined,
    entryReason: 'Pérdida de potencia y vibración al acelerar en carretera.',
    diagnosticReport: undefined,
    diagnosticDate: undefined,
    laborItems: [],
    partsItems: [],
    totalLaborBOB: 0,
    totalPartsBOB: 0,
    totalGeneralBOB: 0,
    clientApprovedAt: undefined,
    lastClientContactDate: '2025-05-12',
    daysWithoutClientResponse: 0,
    hasPendingAdditionalWork: false,
    isSuspendedForAdditionalWork: false,
    statusHistory: [
      { status: 'REGISTRADA', timestamp: '2025-05-12T09:00:00Z', changedBy: 'Recepción (HU-01)' },
    ],
    internalNotes: 'En espera de asignación de bahía y diagnóstico técnico inicial.',
  },
  {
    id: 'ot-006',
    code: 'OT-2025-0106',
    vehiclePlate: '6320-KLA',
    vehicleBrand: 'Volkswagen',
    vehicleModel: 'Gol Trend 1.6 2017',
    vehicleYear: 2017,
    clientName: 'Gonzalo Peñaranda',
    clientDocument: '5019283 LP',
    clientPhone: '+591 70554433',
    clientEmail: 'gonzalo.p@live.com',
    status: 'FINALIZADA',
    assignedBayId: undefined,
    primaryMechanicId: 'MEC-02',
    entryDate: '2025-05-08T11:00:00Z',
    estimatedDeliveryDate: '2025-05-10T16:00:00Z',
    completedAt: '2025-05-10T15:30:00Z',
    entryReason: 'Frenado esponjoso y chillido agudo al desacelerar.',
    diagnosticReport: 'Zapatas traseras cristalizadas y líquido de frenos degradado con humedad superior al 3.5%.',
    diagnosticDate: '2025-05-08T12:00:00Z',
    laborItems: [
      {
        id: 'lab-10',
        description: 'Rectificado de campanas y regulación de frenos traseros',
        estimatedHours: 2.0,
        hourlyRateBOB: 120,
        totalBOB: 240,
        isCompleted: true,
        assignedMechanicId: 'MEC-02',
      },
      {
        id: 'lab-11',
        description: 'Purgado y cambio completo de líquido de frenos DOT 4',
        estimatedHours: 1.0,
        hourlyRateBOB: 120,
        totalBOB: 120,
        isCompleted: true,
        assignedMechanicId: 'MEC-02',
      },
    ],
    partsItems: [
      {
        id: 'pot-12',
        partId: 'REP-FRE-003',
        partCode: 'REP-FRE-003',
        description: 'Líquido de Frenos DOT 4 Bosch 1L',
        quantityRequired: 1,
        quantityUsed: 1,
        unitPriceBOB: 85,
        totalBOB: 85,
        isReserved: true,
        isDeliveredToBay: true,
        status: 'INSTALADO',
      },
    ],
    totalLaborBOB: 360,
    totalPartsBOB: 85,
    totalGeneralBOB: 445,
    clientApprovedAt: '2025-05-08T12:30:00Z',
    clientApprovalMethod: 'PRESENCIAL',
    lastClientContactDate: '2025-05-10',
    daysWithoutClientResponse: 0,
    hasPendingAdditionalWork: false,
    isSuspendedForAdditionalWork: false,
    statusHistory: [
      { status: 'REGISTRADA', timestamp: '2025-05-08T11:00:00Z', changedBy: 'Recepción' },
      { status: 'EN_DIAGNOSTICO', timestamp: '2025-05-08T11:30:00Z', changedBy: 'Roberto Gómez' },
      { status: 'DIAGNOSTICADA', timestamp: '2025-05-08T12:00:00Z', changedBy: 'Roberto Gómez' },
      { status: 'APROBADA', timestamp: '2025-05-08T12:30:00Z', changedBy: 'Cliente Presencial' },
      { status: 'EN_PROGRESO', timestamp: '2025-05-09T08:30:00Z', changedBy: 'Roberto Gómez' },
      { status: 'FINALIZADA', timestamp: '2025-05-10T15:30:00Z', changedBy: 'Roberto Gómez (Control de calidad superado)' },
    ],
    mechanicNotes: 'Prueba de frenado en rodillos OK. Listo para entrega y facturación en BOB.',
  },
];

class MockDatabase {
  private getItem<T>(key: string, defaultData: T): T {
    try {
      const stored = localStorage.getItem(STORAGE_KEY_PREFIX + key);
      if (stored) return JSON.parse(stored) as T;
    } catch {
      // fallback al seed
    }
    return defaultData;
  }

  private setItem<T>(key: string, data: T): void {
    try {
      localStorage.setItem(STORAGE_KEY_PREFIX + key, JSON.stringify(data));
    } catch {
      // almacenamiento no disponible: se mantiene en memoria
    }
  }

  getBays(): Bay[] {
    return this.getItem<Bay[]>('bays', INITIAL_BAYS);
  }

  saveBays(data: Bay[]): void {
    this.setItem('bays', data);
  }

  getMechanics(): Mechanic[] {
    return this.getItem<Mechanic[]>('mechanics', INITIAL_MECHANICS);
  }

  saveMechanics(data: Mechanic[]): void {
    this.setItem('mechanics', data);
  }

  getWorkOrders(): WorkOrder[] {
    return this.getItem<WorkOrder[]>('work_orders', INITIAL_WORK_ORDERS);
  }

  saveWorkOrders(data: WorkOrder[]): void {
    this.setItem('work_orders', data);
  }

  getInventory(): InventoryItem[] {
    return this.getItem<InventoryItem[]>('inventory', INITIAL_INVENTORY);
  }

  saveInventory(data: InventoryItem[]): void {
    this.setItem('inventory', data);
  }

  resetAll(): void {
    this.saveBays(INITIAL_BAYS);
    this.saveMechanics(INITIAL_MECHANICS);
    this.saveWorkOrders(INITIAL_WORK_ORDERS);
    this.saveInventory(INITIAL_INVENTORY);
  }
}

export const mockDb = new MockDatabase();
export const resetStorageToSeed = (): void => mockDb.resetAll();