/**
 * Simulated Database & Persistence Service for Taller Mecánico "Los Fratelli"
 * Persists changes in browser localStorage for a seamless experience.
 */

import type {
  Vehicle,
  Bay,
  Mechanic,
  WorkOrder,
  InventoryItem,
  Budget,
  BillingAccount,
} from '../types/openapi';

const STORAGE_KEY_PREFIX = 'fratelli_workshop_v1_';

export const INITIAL_MECHANICS: Mechanic[] = [
  {
    id: 'MEC-01',
    name: 'Juan Carlos Mamani',
    nickname: 'J.C. Mamani',
    specialty: 'Mecánica General',
    activeOtCount: 2,
    currentBayId: 1,
    phone: '+591 71234567',
  },
  {
    id: 'MEC-02',
    name: 'Roberto Gómez Silva',
    nickname: 'R. Gómez',
    specialty: 'Frenos y Suspensión',
    activeOtCount: 1,
    currentBayId: 2,
    phone: '+591 72345678',
  },
  {
    id: 'MEC-03',
    name: 'Diego Morales Claros',
    nickname: 'D. Morales',
    specialty: 'Electricidad y Diagnóstico',
    activeOtCount: 1,
    currentBayId: 3,
    phone: '+591 73456789',
  },
  {
    id: 'MEC-04',
    name: 'Marco Vargas Rios',
    nickname: 'M. Vargas',
    specialty: 'Transmisiones',
    activeOtCount: 0,
    currentBayId: undefined,
    phone: '+591 74567890',
  },
];

export const INITIAL_BAYS: Bay[] = [
  {
    id: 1,
    code: 'BAHIA-01',
    name: 'Bahía 1: Elevador 4T (Mecánica Pesada)',
    type: 'Elevador Hidráulico 4T',
    status: 'OCUPADA',
    currentWorkOrderId: 'OT-2025-0101',
    currentVehiclePlate: '4589-KXA',
    currentVehicleModel: 'Toyota Hilux 2.8 TD 2021',
    primaryMechanicId: 'MEC-01',
    assistantMechanicId: 'MEC-04',
    startedAt: '2025-05-10T08:30:00Z',
    estimatedCompletionAt: '2025-05-12T17:00:00Z',
    notes: 'Cambio de amortiguadores delanteros y calibración de inyectores.',
  },
  {
    id: 2,
    code: 'BAHIA-02',
    name: 'Bahía 2: Elevador 2 Col. (Frenos y Suspensión)',
    type: 'Elevador 2 Columnas',
    status: 'ESPERA_REPUESTO',
    currentWorkOrderId: 'OT-2025-0102',
    currentVehiclePlate: '3042-XYZ',
    currentVehicleModel: 'Suzuki Grand Vitara 2019',
    primaryMechanicId: 'MEC-02',
    startedAt: '2025-05-09T14:00:00Z',
    estimatedCompletionAt: '2025-05-13T12:00:00Z',
    notes: 'Esperando llegada de kit de embrague reforzado.',
  },
  {
    id: 3,
    code: 'BAHIA-03',
    name: 'Bahía 3: Fosa / Diagnóstico Computarizado',
    type: 'Fosa de Alineación',
    status: 'OCUPADA',
    currentWorkOrderId: 'OT-2025-0105',
    currentVehiclePlate: '2190-LPN',
    currentVehicleModel: 'Nissan Frontier 2.5 2018',
    primaryMechanicId: 'MEC-03',
    startedAt: '2025-05-11T09:00:00Z',
    estimatedCompletionAt: '2025-05-12T14:00:00Z',
    notes: 'Trabajo suspendido por detección de fuga de retén adicional (RN-03).',
  },
  {
    id: 4,
    code: 'BAHIA-04',
    name: 'Bahía 4: Mantenimiento Preventivo / Rápido',
    type: 'Bahía Rápida / Escáner',
    status: 'LIBRE',
    currentWorkOrderId: undefined,
    currentVehiclePlate: undefined,
    currentVehicleModel: undefined,
    primaryMechanicId: undefined,
    notes: 'Disponible para asignación de mantenimiento express o afinado.',
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'VEH-01',
    plate: '4589-KXA',
    brand: 'Toyota',
    model: 'Hilux D/C 4x4',
    year: 2021,
    fuelType: 'DIESEL',
    color: 'Plata Metálico',
    vin: '8AJBA3CD40921820',
    mileage: 64200,
    clientName: 'Alejandro Valenzuela',
    clientDocument: '4892019 LP',
    clientPhone: '+591 70192834',
    clientEmail: 'alejandro.val@gmail.com',
    lastServiceDate: '2024-11-15',
    totalPreviousVisits: 3,
    inspectionChecklist: {
      fuelLevel: '3/4',
      spareTire: true,
      jackAndTools: true,
      documentsInCar: true,
      scratchesOrDents: ['Rayón leve en parachoques trasero derecho'],
      valuableBelongings: 'Gafas de sol en guantera',
    },
  },
  {
    id: 'VEH-02',
    plate: '3042-XYZ',
    brand: 'Suzuki',
    model: 'Grand Vitara 2.4',
    year: 2019,
    fuelType: 'GASOLINA',
    color: 'Blanco Perla',
    vin: '2S3TC4309871234',
    mileage: 82100,
    clientName: 'Carla Patricia Mendoza',
    clientDocument: '6102938 SC',
    clientPhone: '+591 76543210',
    clientEmail: 'carla.mendoza@hotmail.com',
    lastServiceDate: '2024-08-20',
    totalPreviousVisits: 2,
    inspectionChecklist: {
      fuelLevel: '1/2',
      spareTire: true,
      jackAndTools: true,
      documentsInCar: true,
      scratchesOrDents: ['Golpe pequeño en puerta copiloto'],
      valuableBelongings: 'Ninguno',
    },
  },
  {
    id: 'VEH-03',
    plate: '5120-TUV',
    brand: 'Hyundai',
    model: 'Tucson 2.0 GL',
    year: 2020,
    fuelType: 'GASOLINA',
    color: 'Gris Grafito',
    vin: 'KMHD881LAKU09812',
    mileage: 49500,
    clientName: 'Rodrigo Fernández Paz',
    clientDocument: '3490182 CB',
    clientPhone: '+591 77112233',
    clientEmail: 'r.fernandez@pazcorp.bo',
    lastServiceDate: '2024-04-10',
    totalPreviousVisits: 1,
    inspectionChecklist: {
      fuelLevel: '1/4',
      spareTire: true,
      jackAndTools: true,
      documentsInCar: false,
      scratchesOrDents: [],
      valuableBelongings: 'Control portón automático',
    },
  },
  {
    id: 'VEH-04',
    plate: '2190-LPN',
    brand: 'Nissan',
    model: 'Frontier NP300',
    year: 2018,
    fuelType: 'DIESEL',
    color: 'Rojo Burdeos',
    vin: '3N6DD09217823901',
    mileage: 112000,
    clientName: 'Jorge Alberto Quiroga',
    clientDocument: '2981045 LP',
    clientPhone: '+591 71982374',
    clientEmail: 'jorge.quiroga@transporte.bo',
    lastServiceDate: '2024-12-05',
    totalPreviousVisits: 5,
    inspectionChecklist: {
      fuelLevel: 'LLENO',
      spareTire: true,
      jackAndTools: true,
      documentsInCar: true,
      scratchesOrDents: ['Abolladura en compuerta trasera'],
      valuableBelongings: 'Linterna LED y cables puente',
    },
  },
  {
    id: 'VEH-05',
    plate: '4011-HBN',
    brand: 'Toyota',
    model: 'Corolla 1.8 Hybrid',
    year: 2022,
    fuelType: 'HIBRIDO',
    color: 'Azul Noche',
    vin: 'JTDK309812739102',
    mileage: 31000,
    clientName: 'Mariana Gutierrez Arce',
    clientDocument: '7829103 SC',
    clientPhone: '+591 78901234',
    clientEmail: 'mariana.g@gmail.com',
    lastServiceDate: '2025-01-14',
    totalPreviousVisits: 1,
    inspectionChecklist: {
      fuelLevel: '3/4',
      spareTire: true,
      jackAndTools: true,
      documentsInCar: true,
      scratchesOrDents: [],
      valuableBelongings: 'Ninguno',
    },
  },
  {
    id: 'VEH-06',
    plate: '6320-KLA',
    brand: 'Volkswagen',
    model: 'Gol Trend 1.6',
    year: 2017,
    fuelType: 'GASOLINA',
    color: 'Negro',
    vin: '9BWDB09182391029',
    mileage: 95400,
    clientName: 'Gonzalo Peñaranda',
    clientDocument: '5019283 LP',
    clientPhone: '+591 70554433',
    clientEmail: 'gonzalo.p@live.com',
    lastServiceDate: '2024-09-02',
    totalPreviousVisits: 2,
    inspectionChecklist: {
      fuelLevel: '1/2',
      spareTire: true,
      jackAndTools: false,
      documentsInCar: true,
      scratchesOrDents: ['Paragolpe delantero raspado'],
      valuableBelongings: 'Cable USB y soporte magnético celular',
    },
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  // MOTOR
  {
    id: 'REP-MOT-001',
    code: 'REP-MOT-001',
    name: 'Kit Correa de Distribución + Tensor Gates',
    category: 'MOTOR',
    brand: 'Gates',
    compatibleModels: 'Toyota Hilux 2.4/2.8, Fortuner',
    stockAvailable: 8,
    stockReserved: 1,
    stockMinimum: 3,
    unitCostBOB: 420,
    unitPriceBOB: 680,
    locationShelf: 'Estante A-01',
    lastMovementDate: '2025-05-08',
    daysWithoutMovement: 3,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-MOT-002',
    code: 'REP-MOT-002',
    name: 'Bomba de Agua GMB Reforzada',
    category: 'MOTOR',
    brand: 'GMB',
    compatibleModels: 'Suzuki Grand Vitara 2.0/2.4',
    stockAvailable: 4,
    stockReserved: 1,
    stockMinimum: 2,
    unitCostBOB: 280,
    unitPriceBOB: 450,
    locationShelf: 'Estante A-02',
    lastMovementDate: '2025-04-12',
    daysWithoutMovement: 29,
    rotationCategory: 'MEDIA',
  },
  {
    id: 'REP-MOT-003',
    code: 'REP-MOT-003',
    name: 'Juego de Bujías de Iridio NGK (x4)',
    category: 'MOTOR',
    brand: 'NGK Laser Iridium',
    compatibleModels: 'Universal Gasolina / Toyota / Nissan',
    stockAvailable: 24,
    stockReserved: 4,
    stockMinimum: 8,
    unitCostBOB: 180,
    unitPriceBOB: 320,
    locationShelf: 'Estante A-03',
    lastMovementDate: '2025-05-10',
    daysWithoutMovement: 1,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-MOT-004',
    code: 'REP-MOT-004',
    name: 'Retén Trasero de Cigüeñal (Bancada) Original',
    category: 'MOTOR',
    brand: 'Corteco / OEM',
    compatibleModels: 'Nissan Frontier YD25 / NP300',
    stockAvailable: 6,
    stockReserved: 1,
    stockMinimum: 2,
    unitCostBOB: 110,
    unitPriceBOB: 210,
    locationShelf: 'Estante A-04',
    lastMovementDate: '2025-05-11',
    daysWithoutMovement: 0,
    rotationCategory: 'MEDIA',
  },
  {
    id: 'REP-MOT-005',
    code: 'REP-MOT-005',
    name: 'Junta de Tapa de Válvulas Victor Reinz',
    category: 'MOTOR',
    brand: 'Victor Reinz',
    compatibleModels: 'Hyundai Tucson 2.0 / Elantra',
    stockAvailable: 5,
    stockReserved: 0,
    stockMinimum: 2,
    unitCostBOB: 95,
    unitPriceBOB: 180,
    locationShelf: 'Estante A-05',
    lastMovementDate: '2025-01-10',
    daysWithoutMovement: 122, // RN-10 Alert!
    rotationCategory: 'SIN_ROTACION_ALERTA',
  },

  // FRENOS
  {
    id: 'REP-FRE-001',
    code: 'REP-FRE-001',
    name: 'Pastillas de Freno Cerámicas Delanteras Brembo',
    category: 'FRENOS',
    brand: 'Brembo',
    compatibleModels: 'Toyota Hilux, Fortuner 2016-2023',
    stockAvailable: 12,
    stockReserved: 2,
    stockMinimum: 4,
    unitCostBOB: 240,
    unitPriceBOB: 390,
    locationShelf: 'Estante B-01',
    lastMovementDate: '2025-05-09',
    daysWithoutMovement: 2,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-FRE-002',
    code: 'REP-FRE-002',
    name: 'Discos de Freno Ventilados Delanteros (Par)',
    category: 'FRENOS',
    brand: 'Fremax',
    compatibleModels: 'Suzuki Grand Vitara / SX4',
    stockAvailable: 3,
    stockReserved: 0,
    stockMinimum: 2,
    unitCostBOB: 490,
    unitPriceBOB: 780,
    locationShelf: 'Estante B-02',
    lastMovementDate: '2025-04-20',
    daysWithoutMovement: 21,
    rotationCategory: 'MEDIA',
  },
  {
    id: 'REP-FRE-003',
    code: 'REP-FRE-003',
    name: 'Líquido de Frenos DOT 4 Bosch 1L',
    category: 'FRENOS',
    brand: 'Bosch',
    compatibleModels: 'Universal',
    stockAvailable: 35,
    stockReserved: 3,
    stockMinimum: 10,
    unitCostBOB: 45,
    unitPriceBOB: 85,
    locationShelf: 'Estante B-03',
    lastMovementDate: '2025-05-10',
    daysWithoutMovement: 1,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-FRE-004',
    code: 'REP-FRE-004',
    name: 'Zapatas de Freno Traseras Fras-le',
    category: 'FRENOS',
    brand: 'Fras-le',
    compatibleModels: 'Volkswagen Gol Trend / Saveiro',
    stockAvailable: 7,
    stockReserved: 0,
    stockMinimum: 3,
    unitCostBOB: 130,
    unitPriceBOB: 240,
    locationShelf: 'Estante B-04',
    lastMovementDate: '2025-02-15',
    daysWithoutMovement: 86, // RN-10 Alert!
    rotationCategory: 'SIN_ROTACION_ALERTA',
  },

  // SUSPENSION Y DIRECCION
  {
    id: 'REP-SUS-001',
    code: 'REP-SUS-001',
    name: 'Amortiguador Delantero a Gas KYB Excel-G (Unidad)',
    category: 'SUSPENSION_DIRECCION',
    brand: 'KYB',
    compatibleModels: 'Toyota Hilux 4x4 2016-2022',
    stockAvailable: 4,
    stockReserved: 2,
    stockMinimum: 2,
    unitCostBOB: 520,
    unitPriceBOB: 840,
    locationShelf: 'Estante C-01',
    lastMovementDate: '2025-05-09',
    daysWithoutMovement: 2,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-SUS-002',
    code: 'REP-SUS-002',
    name: 'Terminal de Dirección Exterior 555 Japón',
    category: 'SUSPENSION_DIRECCION',
    brand: 'Three Five (555)',
    compatibleModels: 'Nissan Frontier NP300 / Navara',
    stockAvailable: 10,
    stockReserved: 0,
    stockMinimum: 4,
    unitCostBOB: 110,
    unitPriceBOB: 195,
    locationShelf: 'Estante C-02',
    lastMovementDate: '2025-04-28',
    daysWithoutMovement: 13,
    rotationCategory: 'MEDIA',
  },
  {
    id: 'REP-SUS-003',
    code: 'REP-SUS-003',
    name: 'Buje de Horquilla Inferior Reforzado CTR',
    category: 'SUSPENSION_DIRECCION',
    brand: 'CTR Korea',
    compatibleModels: 'Hyundai Tucson / Kia Sportage',
    stockAvailable: 16,
    stockReserved: 0,
    stockMinimum: 6,
    unitCostBOB: 65,
    unitPriceBOB: 120,
    locationShelf: 'Estante C-03',
    lastMovementDate: '2025-01-20',
    daysWithoutMovement: 112, // RN-10 Alert!
    rotationCategory: 'SIN_ROTACION_ALERTA',
  },

  // TRANSMISION
  {
    id: 'REP-TRA-001',
    code: 'REP-TRA-001',
    name: 'Kit de Embrague Completo (Disco, Prensa y Rulemán) Valeo',
    category: 'TRANSMISION',
    brand: 'Valeo',
    compatibleModels: 'Suzuki Grand Vitara 2.4',
    stockAvailable: 2,
    stockReserved: 1,
    stockMinimum: 1,
    unitCostBOB: 890,
    unitPriceBOB: 1450,
    locationShelf: 'Estante D-01',
    lastMovementDate: '2025-05-09',
    daysWithoutMovement: 2,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-TRA-002',
    code: 'REP-TRA-002',
    name: 'Aceite de Transmisión Manual 75W-90 Motul Motylgear 1L',
    category: 'TRANSMISION',
    brand: 'Motul',
    compatibleModels: 'Universal Cajas Manuales y Diferenciales',
    stockAvailable: 22,
    stockReserved: 4,
    stockMinimum: 8,
    unitCostBOB: 80,
    unitPriceBOB: 140,
    locationShelf: 'Estante D-02',
    lastMovementDate: '2025-05-07',
    daysWithoutMovement: 4,
    rotationCategory: 'ALTA',
  },

  // FILTROS Y FLUIDOS
  {
    id: 'REP-FLT-001',
    code: 'REP-FLT-001',
    name: 'Filtro de Aceite Blindado Mann-Filter W 68/3',
    category: 'FILTROS_FLUIDOS',
    brand: 'Mann-Filter',
    compatibleModels: 'Toyota / Suzuki / Nissan',
    stockAvailable: 48,
    stockReserved: 6,
    stockMinimum: 15,
    unitCostBOB: 35,
    unitPriceBOB: 65,
    locationShelf: 'Estante E-01',
    lastMovementDate: '2025-05-11',
    daysWithoutMovement: 0,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-FLT-002',
    code: 'REP-FLT-002',
    name: 'Filtro de Aire Motor Donaldson Alta Eficiencia',
    category: 'FILTROS_FLUIDOS',
    brand: 'Donaldson',
    compatibleModels: 'Toyota Hilux 2.8 TD 2016+',
    stockAvailable: 15,
    stockReserved: 2,
    stockMinimum: 5,
    unitCostBOB: 95,
    unitPriceBOB: 160,
    locationShelf: 'Estante E-02',
    lastMovementDate: '2025-05-09',
    daysWithoutMovement: 2,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-FLT-003',
    code: 'REP-FLT-003',
    name: 'Aceite de Motor Sintético 5W-30 Mobil 1 ESP (Galón 4L)',
    category: 'FILTROS_FLUIDOS',
    brand: 'Mobil 1',
    compatibleModels: 'Gasolina / Diésel Liviano',
    stockAvailable: 18,
    stockReserved: 3,
    stockMinimum: 6,
    unitCostBOB: 290,
    unitPriceBOB: 460,
    locationShelf: 'Estante E-03',
    lastMovementDate: '2025-05-11',
    daysWithoutMovement: 0,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-FLT-004',
    code: 'REP-FLT-004',
    name: 'Filtro de Combustible Diésel Separador de Agua Denso',
    category: 'FILTROS_FLUIDOS',
    brand: 'Denso',
    compatibleModels: 'Nissan Frontier / Mitsubishi L200',
    stockAvailable: 8,
    stockReserved: 1,
    stockMinimum: 3,
    unitCostBOB: 120,
    unitPriceBOB: 210,
    locationShelf: 'Estante E-04',
    lastMovementDate: '2025-05-04',
    daysWithoutMovement: 7,
    rotationCategory: 'MEDIA',
  },
  {
    id: 'REP-FLT-005',
    code: 'REP-FLT-005',
    name: 'Refrigerante Larga Vida 50/50 Rojo Prestone 1 Gal.',
    category: 'FILTROS_FLUIDOS',
    brand: 'Prestone',
    compatibleModels: 'Universal',
    stockAvailable: 28,
    stockReserved: 2,
    stockMinimum: 8,
    unitCostBOB: 85,
    unitPriceBOB: 150,
    locationShelf: 'Estante E-05',
    lastMovementDate: '2025-05-08',
    daysWithoutMovement: 3,
    rotationCategory: 'ALTA',
  },

  // ELECTRICO Y LUCES
  {
    id: 'REP-ELE-001',
    code: 'REP-ELE-001',
    name: 'Batería Libre de Mantenimiento 12V 70Ah Baterías Toyo',
    category: 'ELECTRICO_LUCES',
    brand: 'Toyo',
    compatibleModels: 'Camionetas y SUVs',
    stockAvailable: 5,
    stockReserved: 0,
    stockMinimum: 2,
    unitCostBOB: 540,
    unitPriceBOB: 820,
    locationShelf: 'Estante F-01',
    lastMovementDate: '2025-05-02',
    daysWithoutMovement: 9,
    rotationCategory: 'MEDIA',
  },
  {
    id: 'REP-ELE-002',
    code: 'REP-ELE-002',
    name: 'Juego de Focos LED H4 Philips Ultinon Essential',
    category: 'ELECTRICO_LUCES',
    brand: 'Philips',
    compatibleModels: 'Conector H4 Estándar',
    stockAvailable: 9,
    stockReserved: 0,
    stockMinimum: 3,
    unitCostBOB: 170,
    unitPriceBOB: 290,
    locationShelf: 'Estante F-02',
    lastMovementDate: '2025-04-18',
    daysWithoutMovement: 23,
    rotationCategory: 'MEDIA',
  },
  {
    id: 'REP-ELE-003',
    code: 'REP-ELE-003',
    name: 'Regulador de Voltaje Alternador Valeo',
    category: 'ELECTRICO_LUCES',
    brand: 'Valeo',
    compatibleModels: 'Volkswagen Gol / Fox / Suran',
    stockAvailable: 4,
    stockReserved: 0,
    stockMinimum: 2,
    unitCostBOB: 140,
    unitPriceBOB: 260,
    locationShelf: 'Estante F-03',
    lastMovementDate: '2025-01-05',
    daysWithoutMovement: 127, // RN-10 Alert!
    rotationCategory: 'SIN_ROTACION_ALERTA',
  },

  // CLIMATIZACION
  {
    id: 'REP-CLI-001',
    code: 'REP-CLI-001',
    name: 'Filtro de Cabina / Polen con Carbón Activado Mann',
    category: 'CLIMATIZACION',
    brand: 'Mann-Filter',
    compatibleModels: 'Toyota Hilux / Fortuner / RAV4',
    stockAvailable: 14,
    stockReserved: 1,
    stockMinimum: 4,
    unitCostBOB: 65,
    unitPriceBOB: 125,
    locationShelf: 'Estante G-01',
    lastMovementDate: '2025-05-09',
    daysWithoutMovement: 2,
    rotationCategory: 'ALTA',
  },
  {
    id: 'REP-CLI-002',
    code: 'REP-CLI-002',
    name: 'Gas Refrigerante R134a Genetron Lata 1 Kg',
    category: 'CLIMATIZACION',
    brand: 'Honeywell Genetron',
    compatibleModels: 'Sistemas A/C R134a',
    stockAvailable: 11,
    stockReserved: 0,
    stockMinimum: 3,
    unitCostBOB: 115,
    unitPriceBOB: 210,
    locationShelf: 'Estante G-02',
    lastMovementDate: '2025-04-25',
    daysWithoutMovement: 16,
    rotationCategory: 'MEDIA',
  },
];

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'ot-001',
    code: 'OT-2025-0101',
    vehiclePlate: '4589-KXA',
    vehicleBrand: 'Toyota',
    vehicleModel: 'Hilux D/C 4x4 2021',
    vehicleYear: 2021,
    clientName: 'Alejandro Valenzuela',
    clientDocument: '4892019 LP',
    clientPhone: '+591 70192834',
    clientEmail: 'alejandro.val@gmail.com',
    status: 'EN_PROGRESO',
    assignedBayId: 1,
    primaryMechanicId: 'MEC-01',
    assistantMechanicId: 'MEC-04',
    entryDate: '2025-05-10T08:30:00Z',
    estimatedDeliveryDate: '2025-05-12T17:00:00Z',
    entryReason: 'Ruido metálico en tren delantero al pasar baches y mantenimiento de 60,000 km.',
    diagnosticReport: 'Amortiguadores delanteros con fuga de aceite hidráulico. Desgaste severo en pastillas de freno (quedan 1.5mm). Se recomienda cambio completo de kit de frenos y amortiguadores.',
    laborItems: [
      {
        id: 'lab-01',
        description: 'Reemplazo de amortiguadores delanteros y alineación láser',
        estimatedHours: 3.5,
        hourlyRateBOB: 120,
        totalBOB: 420,
        isCompleted: true,
        assignedMechanicId: 'MEC-01',
      },
      {
        id: 'lab-02',
        description: 'Cambio de pastillas de freno y purgado de circuito hidráulico',
        estimatedHours: 1.5,
        hourlyRateBOB: 120,
        totalBOB: 180,
        isCompleted: false,
        assignedMechanicId: 'MEC-04',
      },
      {
        id: 'lab-03',
        description: 'Mantenimiento preventivo: cambio de aceite motor, filtro aceite, aire y cabina',
        estimatedHours: 1.0,
        hourlyRateBOB: 120,
        totalBOB: 120,
        isCompleted: false,
        assignedMechanicId: 'MEC-01',
      },
    ],
    partsItems: [
      {
        id: 'pot-01',
        partId: 'REP-SUS-001',
        partCode: 'REP-SUS-001',
        description: 'Amortiguador Delantero a Gas KYB Excel-G (Unidad)',
        quantityRequired: 2,
        quantityUsed: 2,
        unitPriceBOB: 840,
        totalBOB: 1680,
        isReserved: true,
        isDeliveredToBay: true,
        status: 'INSTALADO',
      },
      {
        id: 'pot-02',
        partId: 'REP-FRE-001',
        partCode: 'REP-FRE-001',
        description: 'Pastillas de Freno Cerámicas Delanteras Brembo',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 390,
        totalBOB: 390,
        isReserved: true,
        isDeliveredToBay: true,
        status: 'RESERVADO',
      },
      {
        id: 'pot-03',
        partId: 'REP-FLT-003',
        partCode: 'REP-FLT-003',
        description: 'Aceite de Motor Sintético 5W-30 Mobil 1 ESP (Galón)',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 460,
        totalBOB: 460,
        isReserved: true,
        isDeliveredToBay: false,
        status: 'RESERVADO',
      },
      {
        id: 'pot-04',
        partId: 'REP-FLT-001',
        partCode: 'REP-FLT-001',
        description: 'Filtro de Aceite Blindado Mann-Filter W 68/3',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 65,
        totalBOB: 65,
        isReserved: true,
        isDeliveredToBay: false,
        status: 'RESERVADO',
      },
    ],
    totalLaborBOB: 720,
    totalPartsBOB: 2595,
    totalGeneralBOB: 3315,
    clientApprovedAt: '2025-05-10T10:15:00Z',
    clientApprovalMethod: 'PORTAL_WEB',
    lastClientContactDate: '2025-05-10',
    daysWithoutClientResponse: 0,
    hasPendingAdditionalWork: false,
    isSuspendedForAdditionalWork: false,
    statusHistory: [
      { status: 'REGISTRADA', timestamp: '2025-05-10T08:30:00Z', changedBy: 'Recepción (Ana Morales)' },
      { status: 'DIAGNOSTICADA', timestamp: '2025-05-10T09:30:00Z', changedBy: 'Juan Carlos Mamani' },
      { status: 'PRESUPUESTADA', timestamp: '2025-05-10T09:45:00Z', changedBy: 'Jefe Taller (Ing. Sergio Fratelli)' },
      { status: 'APROBADA', timestamp: '2025-05-10T10:15:00Z', changedBy: 'Cliente (Portal Web)' },
      { status: 'EN_PROGRESO', timestamp: '2025-05-10T11:00:00Z', changedBy: 'Jefe Taller (Asignado a Bahía 1)' },
    ],
    mechanicNotes: 'Amortiguadores instalados y torqueados según manual de fábrica (115 Nm). Procediendo con cambio de pastillas.',
  },
  {
    id: 'ot-002',
    code: 'OT-2025-0102',
    vehiclePlate: '3042-XYZ',
    vehicleBrand: 'Suzuki',
    vehicleModel: 'Grand Vitara 2.4 2019',
    vehicleYear: 2019,
    clientName: 'Carla Patricia Mendoza',
    clientDocument: '6102938 SC',
    clientPhone: '+591 76543210',
    clientEmail: 'carla.mendoza@hotmail.com',
    status: 'EN_ESPERA_REPUESTO',
    assignedBayId: 2,
    primaryMechanicId: 'MEC-02',
    entryDate: '2025-05-09T14:00:00Z',
    estimatedDeliveryDate: '2025-05-13T12:00:00Z',
    entryReason: 'Pedal de embrague muy duro y patina en subidas pronunciadas.',
    diagnosticReport: 'Disco de embrague desgastado hasta los remaches, placa recalentada con signos de fatiga térmica. Requiere kit de embrague completo y rectificado de volante bimasa.',
    laborItems: [
      {
        id: 'lab-04',
        description: 'Desmontaje de caja de cambios, reemplazo kit de embrague y montaje',
        estimatedHours: 6.0,
        hourlyRateBOB: 120,
        totalBOB: 720,
        isCompleted: false,
        assignedMechanicId: 'MEC-02',
      },
      {
        id: 'lab-05',
        description: 'Envío y control de rectificado de volante bimasa',
        estimatedHours: 1.0,
        hourlyRateBOB: 120,
        totalBOB: 120,
        isCompleted: true,
        assignedMechanicId: 'MEC-02',
      },
    ],
    partsItems: [
      {
        id: 'pot-05',
        partId: 'REP-TRA-001',
        partCode: 'REP-TRA-001',
        description: 'Kit de Embrague Completo (Disco, Prensa y Rulemán) Valeo',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 1450,
        totalBOB: 1450,
        isReserved: true,
        isDeliveredToBay: false,
        status: 'EN_ESPERA_IMPORTACION',
      },
      {
        id: 'pot-06',
        partId: 'REP-TRA-002',
        partCode: 'REP-TRA-002',
        description: 'Aceite de Transmisión Manual 75W-90 Motul 1L',
        quantityRequired: 3,
        quantityUsed: 0,
        unitPriceBOB: 140,
        totalBOB: 420,
        isReserved: true,
        isDeliveredToBay: false,
        status: 'RESERVADO',
      },
    ],
    totalLaborBOB: 840,
    totalPartsBOB: 1870,
    totalGeneralBOB: 2710,
    clientApprovedAt: '2025-05-09T16:00:00Z',
    clientApprovalMethod: 'WHATSAPP_CONFIRMADO',
    lastClientContactDate: '2025-05-11',
    daysWithoutClientResponse: 0,
    hasPendingAdditionalWork: false,
    isSuspendedForAdditionalWork: false,
    statusHistory: [
      { status: 'REGISTRADA', timestamp: '2025-05-09T14:00:00Z', changedBy: 'Recepción' },
      { status: 'DIAGNOSTICADA', timestamp: '2025-05-09T15:10:00Z', changedBy: 'Roberto Gómez' },
      { status: 'PRESUPUESTADA', timestamp: '2025-05-09T15:30:00Z', changedBy: 'Jefe Taller' },
      { status: 'APROBADA', timestamp: '2025-05-09T16:00:00Z', changedBy: 'Cliente WhatsApp' },
      { status: 'EN_PROGRESO', timestamp: '2025-05-09T16:30:00Z', changedBy: 'Roberto Gómez' },
      { status: 'EN_ESPERA_REPUESTO', timestamp: '2025-05-10T10:00:00Z', changedBy: 'Jefe Taller (Demora proveedor Valeo)' },
    ],
    mechanicNotes: 'Caja bajada. Volante rectificado ya llegó. Esperando que Almacén entregue el kit de embrague Valeo.',
  },
  {
    id: 'ot-003',
    code: 'OT-2025-0103',
    vehiclePlate: '5120-TUV',
    vehicleBrand: 'Hyundai',
    vehicleModel: 'Tucson 2.0 GL 2020',
    vehicleYear: 2020,
    clientName: 'Rodrigo Fernández Paz',
    clientDocument: '3490182 CB',
    clientPhone: '+591 77112233',
    clientEmail: 'r.fernandez@pazcorp.bo',
    status: 'PRESUPUESTADA',
    assignedBayId: undefined,
    primaryMechanicId: 'MEC-03',
    entryDate: '2025-04-24T10:00:00Z',
    estimatedDeliveryDate: '2025-05-18T18:00:00Z',
    entryReason: 'Check Engine encendido y pérdida súbita de potencia al acelerar en pendientes.',
    diagnosticReport: 'Falla en bobinas de encendido cilindro 2 y 4 + sensor de oxígeno banco 1 descalibrado. Presupuesto enviado a cliente el 25 de abril.',
    laborItems: [
      {
        id: 'lab-06',
        description: 'Diagnóstico escáner avanzado y reemplazo de bobinas con bujías',
        estimatedHours: 2.0,
        hourlyRateBOB: 120,
        totalBOB: 240,
        isCompleted: false,
      },
    ],
    partsItems: [
      {
        id: 'pot-07',
        partId: 'REP-MOT-003',
        partCode: 'REP-MOT-003',
        description: 'Juego de Bujías de Iridio NGK (x4)',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 320,
        totalBOB: 320,
        isReserved: false,
        isDeliveredToBay: false,
        status: 'PENDIENTE',
      },
    ],
    totalLaborBOB: 240,
    totalPartsBOB: 320,
    totalGeneralBOB: 560,
    clientApprovedAt: undefined,
    lastClientContactDate: '2025-04-25',
    daysWithoutClientResponse: 17, // > 15 days! RN-06 alert triggered!
    hasPendingAdditionalWork: false,
    isSuspendedForAdditionalWork: false,
    statusHistory: [
      { status: 'REGISTRADA', timestamp: '2025-04-24T10:00:00Z', changedBy: 'Recepción' },
      { status: 'DIAGNOSTICADA', timestamp: '2025-04-24T15:00:00Z', changedBy: 'Diego Morales' },
      { status: 'PRESUPUESTADA', timestamp: '2025-04-25T09:00:00Z', changedBy: 'Jefe Taller (Presupuesto enviado por Email/WhatsApp)' },
    ],
    internalNotes: 'ALERTA RN-06: 17 días sin respuesta del cliente. Llamar a número alternativo o remitir aviso de custodia / costo de parqueo.',
  },
  {
    id: 'ot-004',
    code: 'OT-2025-0104',
    vehiclePlate: '4011-HBN',
    vehicleBrand: 'Toyota',
    vehicleModel: 'Corolla 1.8 Hybrid 2022',
    vehicleYear: 2022,
    clientName: 'Mariana Gutierrez Arce',
    clientDocument: '7829103 SC',
    clientPhone: '+591 78901234',
    clientEmail: 'mariana.g@gmail.com',
    status: 'APROBADA',
    assignedBayId: undefined, // En cola para ingresar a bahía libre
    primaryMechanicId: 'MEC-01',
    entryDate: '2025-05-11T14:30:00Z',
    estimatedDeliveryDate: '2025-05-13T16:00:00Z',
    entryReason: 'Mantenimiento de 30,000 km, rotación de neumáticos y revisión de sistema de frenos regenerativos.',
    diagnosticReport: 'Vehículo híbrido en excelente estado. Requiere cambio de aceite sintético 0W-20, filtro de aceite, filtro de cabina y prueba de batería auxiliar 12V.',
    laborItems: [
      {
        id: 'lab-07',
        description: 'Mantenimiento programado 30,000 km + Inspección híbrida',
        estimatedHours: 2.0,
        hourlyRateBOB: 120,
        totalBOB: 240,
        isCompleted: false,
      },
    ],
    partsItems: [
      {
        id: 'pot-08',
        partId: 'REP-FLT-001',
        partCode: 'REP-FLT-001',
        description: 'Filtro de Aceite Blindado Mann-Filter W 68/3',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 65,
        totalBOB: 65,
        isReserved: true,
        isDeliveredToBay: false,
        status: 'RESERVADO',
      },
      {
        id: 'pot-09',
        partId: 'REP-CLI-001',
        partCode: 'REP-CLI-001',
        description: 'Filtro de Cabina con Carbón Activado Mann',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 125,
        totalBOB: 125,
        isReserved: true,
        isDeliveredToBay: false,
        status: 'RESERVADO',
      },
    ],
    totalLaborBOB: 240,
    totalPartsBOB: 190,
    totalGeneralBOB: 430,
    clientApprovedAt: '2025-05-11T16:00:00Z',
    clientApprovalMethod: 'PORTAL_WEB',
    lastClientContactDate: '2025-05-11',
    daysWithoutClientResponse: 0,
    hasPendingAdditionalWork: false,
    isSuspendedForAdditionalWork: false,
    statusHistory: [
      { status: 'REGISTRADA', timestamp: '2025-05-11T14:30:00Z', changedBy: 'Recepción' },
      { status: 'DIAGNOSTICADA', timestamp: '2025-05-11T15:20:00Z', changedBy: 'Juan Carlos Mamani' },
      { status: 'PRESUPUESTADA', timestamp: '2025-05-11T15:40:00Z', changedBy: 'Jefe Taller' },
      { status: 'APROBADA', timestamp: '2025-05-11T16:00:00Z', changedBy: 'Cliente (Portal Web)' },
    ],
    internalNotes: 'Cliente aprobó de inmediato. Asignar a Bahía 4 apenas termine turno.',
  },
  {
    id: 'ot-005',
    code: 'OT-2025-0105',
    vehiclePlate: '2190-LPN',
    vehicleBrand: 'Nissan',
    vehicleModel: 'Frontier NP300 2018',
    vehicleYear: 2018,
    clientName: 'Jorge Alberto Quiroga',
    clientDocument: '2981045 LP',
    clientPhone: '+591 71982374',
    clientEmail: 'jorge.quiroga@transporte.bo',
    status: 'DIAGNOSTICADA',
    assignedBayId: 3,
    primaryMechanicId: 'MEC-03',
    entryDate: '2025-05-11T09:00:00Z',
    estimatedDeliveryDate: '2025-05-14T17:00:00Z',
    entryReason: 'Cambio de pastillas de freno y cambio de aceite de motor.',
    diagnosticReport: 'Durante la inspección en elevador, se detectó FUGA ACTIVA DE ACEITE en el Retén Trasero de Cigüeñal (Bancada). Requiere desmontar caja para reemplazar retén. Trabajo suspendido automáticamente hasta aprobación del cliente (RN-03).',
    laborItems: [
      {
        id: 'lab-08',
        description: 'Cambio básico de aceite y filtro',
        estimatedHours: 1.0,
        hourlyRateBOB: 120,
        totalBOB: 120,
        isCompleted: true,
        assignedMechanicId: 'MEC-03',
      },
      {
        id: 'lab-09',
        description: '[ADICIONAL RN-03] Desmontaje de caja y reemplazo de retén de bancada',
        estimatedHours: 4.5,
        hourlyRateBOB: 120,
        totalBOB: 540,
        isCompleted: false,
        assignedMechanicId: 'MEC-03',
      },
    ],
    partsItems: [
      {
        id: 'pot-10',
        partId: 'REP-FLT-001',
        partCode: 'REP-FLT-001',
        description: 'Filtro de Aceite Blindado Mann-Filter W 68/3',
        quantityRequired: 1,
        quantityUsed: 1,
        unitPriceBOB: 65,
        totalBOB: 65,
        isReserved: true,
        isDeliveredToBay: true,
        status: 'INSTALADO',
      },
      {
        id: 'pot-11',
        partId: 'REP-MOT-004',
        partCode: 'REP-MOT-004',
        description: '[ADICIONAL RN-03] Retén Trasero de Cigüeñal Original',
        quantityRequired: 1,
        quantityUsed: 0,
        unitPriceBOB: 210,
        totalBOB: 210,
        isReserved: true,
        isDeliveredToBay: false,
        status: 'PENDIENTE',
      },
    ],
    totalLaborBOB: 660,
    totalPartsBOB: 275,
    totalGeneralBOB: 935,
    clientApprovedAt: undefined,
    lastClientContactDate: '2025-05-11',
    daysWithoutClientResponse: 0,
    hasPendingAdditionalWork: true, // RN-03
    additionalWorkDescription: 'Detección de fuga activa de aceite en retén de bancada. Requiere desmontar caja de cambios y colocar retén nuevo (+540 Bs. mano de obra, +210 Bs. repuesto).',
    additionalWorkCostBOB: 750,
    isSuspendedForAdditionalWork: true, // RN-03 Flag
    statusHistory: [
      { status: 'REGISTRADA', timestamp: '2025-05-11T09:00:00Z', changedBy: 'Recepción' },
      { status: 'DIAGNOSTICADA', timestamp: '2025-05-11T10:30:00Z', changedBy: 'Diego Morales (Detectó daño adicional)' },
    ],
    mechanicNotes: 'ATENCIÓN RN-03: Fuga severa en retén. No armar hasta que el cliente autorice el trabajo extra de 750 BOB.',
  },
  {
    id: 'ot-006',
    code: 'OT-2025-0106',
    vehiclePlate: '6320-KLA',
    vehicleBrand: 'Volkswagen',
    vehicleModel: 'Gol Trend 1.6 2017',
    vehicleYear: 2017,
    clientName: 'Gonzalo Peñaranda',
    clientDocument: '5019283 LP',
    clientPhone: '+591 70554433',
    clientEmail: 'gonzalo.p@live.com',
    status: 'FINALIZADA',
    assignedBayId: undefined,
    primaryMechanicId: 'MEC-02',
    entryDate: '2025-05-08T11:00:00Z',
    estimatedDeliveryDate: '2025-05-10T16:00:00Z',
    completedAt: '2025-05-10T15:30:00Z',
    entryReason: 'Frenado esponjoso y chillido agudo al desacelerar.',
    diagnosticReport: 'Zapatas traseras cristalizadas y líquido de frenos degradado con humedad superior al 3.5%.',
    laborItems: [
      {
        id: 'lab-10',
        description: 'Rectificado de campanas y regulación de frenos traseros',
        estimatedHours: 2.0,
        hourlyRateBOB: 120,
        totalBOB: 240,
        isCompleted: true,
        assignedMechanicId: 'MEC-02',
      },
      {
        id: 'lab-11',
        description: 'Purgado y cambio completo de líquido de frenos DOT 4',
        estimatedHours: 1.0,
        hourlyRateBOB: 120,
        totalBOB: 120,
        isCompleted: true,
        assignedMechanicId: 'MEC-02',
      },
    ],
    partsItems: [
      {
        id: 'pot-12',
        partId: 'REP-FRE-003',
        partCode: 'REP-FRE-003',
        description: 'Líquido de Frenos DOT 4 Bosch 1L',
        quantityRequired: 1,
        quantityUsed: 1,
        unitPriceBOB: 85,
        totalBOB: 85,
        isReserved: true,
        isDeliveredToBay: true,
        status: 'INSTALADO',
      },
    ],
    totalLaborBOB: 360,
    totalPartsBOB: 85,
    totalGeneralBOB: 445,
    clientApprovedAt: '2025-05-08T12:30:00Z',
    clientApprovalMethod: 'PRESENCIAL',
    lastClientContactDate: '2025-05-10',
    daysWithoutClientResponse: 0,
    hasPendingAdditionalWork: false,
    isSuspendedForAdditionalWork: false,
    statusHistory: [
      { status: 'REGISTRADA', timestamp: '2025-05-08T11:00:00Z', changedBy: 'Recepción' },
      { status: 'DIAGNOSTICADA', timestamp: '2025-05-08T12:00:00Z', changedBy: 'Roberto Gómez' },
      { status: 'PRESUPUESTADA', timestamp: '2025-05-08T12:15:00Z', changedBy: 'Jefe Taller' },
      { status: 'APROBADA', timestamp: '2025-05-08T12:30:00Z', changedBy: 'Cliente Presencial' },
      { status: 'EN_PROGRESO', timestamp: '2025-05-09T08:30:00Z', changedBy: 'Roberto Gómez' },
      { status: 'FINALIZADA', timestamp: '2025-05-10T15:30:00Z', changedBy: 'Roberto Gómez (Control de calidad superado)' },
    ],
    mechanicNotes: 'Prueba de frenado en rodillos OK. Freno de mano calibrado a 4 clics. Listo para entrega y facturación en BOB.',
  },
];

export const INITIAL_BILLING: BillingAccount[] = [
  {
    id: 'fac-001',
    workOrderId: 'ot-006',
    invoiceCode: 'FAC-2025-0089',
    issueDate: '2025-05-10',
    clientName: 'Gonzalo Peñaranda',
    clientNitCI: '5019283 LP',
    clientPhone: '+591 70554433',
    vehiclePlate: '6320-KLA',
    vehicleDescription: 'Volkswagen Gol Trend 1.6 2017',
    laborTotalBOB: 360,
    partsTotalBOB: 85,
    discountBOB: 0,
    taxAmountBOB: 57.85,
    totalAmountBOB: 445,
    paymentStatus: 'CANCELADO_TOTAL',
    advancePaymentBOB: 0,
    balanceDueBOB: 0,
    paymentMethod: 'TRANSFERENCIA_QR',
    paidAt: '2025-05-10T16:00:00Z',
    receiptType: 'FACTURA',
  },
  {
    id: 'fac-002',
    workOrderId: 'ot-001',
    invoiceCode: 'REC-2025-0090',
    issueDate: '2025-05-11',
    clientName: 'Alejandro Valenzuela',
    clientNitCI: '4892019 LP',
    clientPhone: '+591 70192834',
    vehiclePlate: '4589-KXA',
    vehicleDescription: 'Toyota Hilux D/C 4x4 2021',
    laborTotalBOB: 720,
    partsTotalBOB: 2595,
    discountBOB: 100,
    taxAmountBOB: 0,
    totalAmountBOB: 3215,
    paymentStatus: 'ANTICIPO',
    advancePaymentBOB: 1500,
    balanceDueBOB: 1715,
    paymentMethod: 'EFECTIVO',
    paidAt: '2025-05-10T10:15:00Z',
    receiptType: 'RECIBO_OFICIAL',
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: 'bud-001',
    workOrderId: 'ot-001',
    otCode: 'OT-2025-0101',
    vehiclePlate: '4589-KXA',
    clientName: 'Alejandro Valenzuela',
    clientDocument: '4892019 LP',
    createdAt: '2025-05-10T09:45:00Z',
    validUntil: '2025-05-25T23:59:59Z',
    laborSubtotalBOB: 720,
    partsSubtotalBOB: 2595,
    discountBOB: 0,
    totalBOB: 3315,
    status: 'APROBADO',
    approvalDate: '2025-05-10T10:15:00Z',
    approvalToken: 'TOK-AP-9921',
    isAdditionalWorkBudget: false,
  },
  {
    id: 'bud-002',
    workOrderId: 'ot-003',
    otCode: 'OT-2025-0103',
    vehiclePlate: '5120-TUV',
    clientName: 'Rodrigo Fernández Paz',
    clientDocument: '3490182 CB',
    createdAt: '2025-04-25T09:00:00Z',
    validUntil: '2025-05-10T23:59:59Z',
    laborSubtotalBOB: 240,
    partsSubtotalBOB: 320,
    discountBOB: 0,
    totalBOB: 560,
    status: 'EXPIRADO', // > 15 days
    isAdditionalWorkBudget: false,
  },
  {
    id: 'bud-003',
    workOrderId: 'ot-005',
    otCode: 'OT-2025-0105',
    vehiclePlate: '2190-LPN',
    clientName: 'Jorge Alberto Quiroga',
    clientDocument: '2981045 LP',
    createdAt: '2025-05-11T10:45:00Z',
    validUntil: '2025-05-26T23:59:59Z',
    laborSubtotalBOB: 540,
    partsSubtotalBOB: 210,
    discountBOB: 0,
    totalBOB: 750,
    status: 'ENVIADO_CLIENTE',
    isAdditionalWorkBudget: true,
  },
];

// LocalStorage Helper with fallback
class MockDatabase {
  private getItem<T>(key: string, defaultData: T): T {
    try {
      const stored = localStorage.getItem(STORAGE_KEY_PREFIX + key);
      if (stored) return JSON.parse(stored);
    } catch {
      // ignore
    }
    return defaultData;
  }

  private setItem<T>(key: string, data: T): void {
    try {
      localStorage.setItem(STORAGE_KEY_PREFIX + key, JSON.stringify(data));
    } catch {
      // ignore
    }
  }

  // Getters
  getVehicles(): Vehicle[] {
    return this.getItem<Vehicle[]>('vehicles', INITIAL_VEHICLES);
  }

  getBays(): Bay[] {
    return this.getItem<Bay[]>('bays', INITIAL_BAYS);
  }

  getMechanics(): Mechanic[] {
    return this.getItem<Mechanic[]>('mechanics', INITIAL_MECHANICS);
  }

  getWorkOrders(): WorkOrder[] {
    return this.getItem<WorkOrder[]>('work_orders', INITIAL_WORK_ORDERS);
  }

  getInventory(): InventoryItem[] {
    return this.getItem<InventoryItem[]>('inventory', INITIAL_INVENTORY);
  }

  getBudgets(): Budget[] {
    return this.getItem<Budget[]>('budgets', INITIAL_BUDGETS);
  }

  getBilling(): BillingAccount[] {
    return this.getItem<BillingAccount[]>('billing', INITIAL_BILLING);
  }

  // Setters / Updates
  saveVehicles(data: Vehicle[]) {
    this.setItem('vehicles', data);
  }

  saveBays(data: Bay[]) {
    this.setItem('bays', data);
  }

  saveMechanics(data: Mechanic[]) {
    this.setItem('mechanics', data);
  }

  saveWorkOrders(data: WorkOrder[]) {
    this.setItem('work_orders', data);
  }

  saveInventory(data: InventoryItem[]) {
    this.setItem('inventory', data);
  }

  saveBudgets(data: Budget[]) {
    this.setItem('budgets', data);
  }

  saveBilling(data: BillingAccount[]) {
    this.setItem('billing', data);
  }

  resetAll() {
    this.saveVehicles(INITIAL_VEHICLES);
    this.saveBays(INITIAL_BAYS);
    this.saveMechanics(INITIAL_MECHANICS);
    this.saveWorkOrders(INITIAL_WORK_ORDERS);
    this.saveInventory(INITIAL_INVENTORY);
    this.saveBudgets(INITIAL_BUDGETS);
    this.saveBilling(INITIAL_BILLING);
  }
}

export const mockDb = new MockDatabase();
export const resetStorageToSeed = () => mockDb.resetAll();
