/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{plate}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get vehicle technical history (US-01, RN-20) */
        get: operations["WorkOrdersController_getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register vehicle entry and create work order (US-01, RN-01, RN-18) */
        post: operations["WorkOrdersController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-orders/{id}/assign-mechanic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign a work order to a mechanic (US-04, RN-14) */
        patch: operations["AssignWorkOrderController_assign"];
        trace?: never;
    };
    "/api/v1/work-orders/assigned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the work orders assigned to the authenticated mechanic (US-03, RN-04) */
        get: operations["AssignedOrdersController_getAssigned"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-orders/assigned/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an assigned work order technical detail (US-03) */
        get: operations["AssignedOrdersController_getAssignedDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/vehicle-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current status of a vehicle without authentication (US-02, RN-17) */
        get: operations["VehicleStatusController_query"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterVehicleEntryDto: Record<string, never>;
        AssignWorkOrderDto: Record<string, never>;
        AssignWorkOrderResponseDto: Record<string, never>;
        AssignedWorkOrderResponseDto: {
            /** @description Work order id */
            id: string;
            /** @description Vehicle id */
            vehicleId: string;
            /** @description Vehicle license plate */
            plate: string;
            /** @description Current work order status */
            status: string;
            /** @description Initial complaint reported by the customer */
            initialComplaint: string;
            /** @description Date when the work order was assigned */
            assignedAt: Record<string, never> | null;
        };
        ListAssignedWorkOrdersResponseDto: {
            /** @description Page of assigned work orders */
            data: components["schemas"]["AssignedWorkOrderResponseDto"][];
            /** @description Total number of assigned work orders */
            total: number;
            /** @description Current page number */
            page: number;
            /** @description Number of items per page */
            pageSize: number;
        };
        VehicleSummaryDto: {
            /** @description Vehicle brand */
            brand: string;
            /** @description Vehicle model */
            model: string;
            /** @description Vehicle year */
            year: number;
        };
        VehicleStatusResponseDto: {
            /** @description Work order id */
            workOrderId: string;
            /** @description Vehicle license plate */
            plate: string;
            /** @description Vehicle summary */
            vehicle: components["schemas"]["VehicleSummaryDto"];
            /** @description Customer name */
            customerName: string;
            /** @description Initial complaint reported by the customer */
            initialComplaint: string;
            /**
             * Format: date-time
             * @description Work order creation date
             */
            createdAt: string;
            /** @description Current work order status */
            status: string;
            /** @description Human readable stage of the attention */
            stage: string;
            /** @description Whether the vehicle is ready for pickup */
            readyForPickup: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkOrdersController_getHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plate: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkOrdersController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterVehicleEntryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Electric vehicles are not accepted */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssignWorkOrderController_assign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignWorkOrderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignWorkOrderResponseDto"];
                };
            };
            /** @description Workshop lead role is required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssignedOrdersController_getAssigned: {
        parameters: {
            query?: {
                /** @description Page number, 1-based */
                page?: number;
                /** @description Number of items per page */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAssignedWorkOrdersResponseDto"];
                };
            };
            /** @description Authentication is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mechanic role is required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssignedOrdersController_getAssignedDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The work order is not assigned to this mechanic */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VehicleStatusController_query: {
        parameters: {
            query: {
                /** @description Vehicle license plate used for the public lookup (RN-17) */
                plate: string;
                /** @description Customer identification document used for the public lookup (RN-17) */
                identification: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleStatusResponseDto"];
                };
            };
            /** @description Invalid or missing query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid work order found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}

export interface WorkOrderListItem {
  id: string;
  vehicleId: string;
  plate: string;
  vehicleBrand: string;
  vehicleModel: string;
  vehicleYear: number;
  customerName: string;
  customerIdentification: string;
  initialComplaint: string;
  status: string;
  createdAt: string;
  mechanicId: string | null;
}

export interface ListResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
}

export interface AssignedWorkOrder {
  id: string;
  vehicleId: string;
  plate: string;
  status: string;
  initialComplaint: string;
  assignedAt: string | null;
}

export interface AssignedWorkOrderDetail extends AssignedWorkOrder {
  vehicle: { plate: string; brand: string; model: string; year: number };
}

export interface VehicleStatus {
  workOrderId: string;
  plate: string;
  vehicle: { brand: string; model: string; year: number };
  customerName: string;
  initialComplaint: string;
  createdAt: string;
  status: string;
  stage: string;
  readyForPickup: boolean;
}

export interface Mechanic {
  id: string;
  isActive: boolean;
}
